export * from "./operational";
export * from "./panels";
export * from "./alerts";
export * from "./dashboard";
export * from "./config";
export * from "./country"
export * from "./exportAlert"

import { productsList, ordersFilter, exportProductsList } from "./panels";

import { alerts, updateAlert, alertsFilter, updateManyAlert } from "./alerts";

import { exportOrderItemAlert, updateExportOrderItemAlert, updateManyExportOrderItemAlert } from "./exportAlert";

import { country } from "./country"

import {
  orderItemsDelay,
  orderItensDelayFilter
} from "./dashboard"

import {
  orderItem,
  orderItems,
  orderItemLocation,
  orderItemShipmentSubscribe,
  orderItemShipmentTracking,
  orderItemStatus,
  exportOrderItems,
  cancelOrderItens,
  newUserFavorite,
  deleteUserFavorite,
  operationalFilterData,
  justifications,
  newJustification,
  getJustification,
  orderItemProcessTypes,
  orderItemFlightLocation,
  orderItemFlightSubscribe,
  orderItemFlightTracking,
  updateOrderItem,
  createOrderFiles,
  searchOrderOptions,
  showOrderFiles,
  updateOrderFile,
  orderItemSelectedIdsReducer,
  orderItemJustificationMany,
  updateProcessCritical,
  getExportOrderJustification,
  newExportOrderJustification,
} from "./operational";

import {
  company,
  alertTypes,
  alertType,
  newAlertType,
  updateAlertType,
  deleteAlertType,
  // Products
  products,
  updateProduct, 
  // Credit History
  serviceType,
  creditHistories,
  creditHistory,
  newCreditHistory,
  updateCreditHistory,
  deleteCreditHistory,
  exportCreditHistories,
  creditHistoriesFilterData,
  responsibles,
  responsible,
  newResponsible,
  updateResponsible,
  deleteResponsible,
  productFetch,
  updateRelatedProduct,
  productPaginate,
  productFilterData,
  justificationTypes,
  newJustificationType,
  deleteJustificationType,
  showJustificationType,
  updateJustificationType,
  //transit Time 
  newTrasitTime,
  deleteTransitTime,
  transitTime,
  updateTransitTime,
  showTransitTime,
  supplierList,
  userSupplierList,
  newSupplier,
  responsibleSupplierList,
  carrier,
  client,
  deleteResponsibleSupplier,
  newUserSupplier,
  updateSupplier,
  createUserSupplier
} from "./config";

import { listOrderFiles } from "./operational";

export const comexReducers = {
  productsList,
  ordersFilter,
  exportProductsList,
  alerts,
  updateAlert,
  alertsFilter,
  orderItemsDelay,
  orderItensDelayFilter,
  orderItem,
  orderItems,
  orderItemLocation,
  orderItemShipmentSubscribe,
  orderItemShipmentTracking,
  orderItemStatus,
  exportOrderItems,
  cancelOrderItens,
  newUserFavorite,
  deleteUserFavorite,
  operationalFilterData,
  justifications,
  newJustification,
  getJustification,
  getExportOrderJustification,
  newExportOrderJustification,
  orderItemProcessTypes,
  orderItemFlightLocation,
  orderItemFlightSubscribe,
  orderItemFlightTracking,
  company,
  alertTypes,
  alertType,
  newAlertType,
  updateAlertType,
  deleteAlertType,
  products,
  updateProduct,
  serviceType,
  creditHistories,
  creditHistory,
  newCreditHistory,
  updateCreditHistory,
  deleteCreditHistory,
  exportCreditHistories,
  creditHistoriesFilterData,
  responsibles,
  responsible,
  newResponsible,
  updateResponsible,
  deleteResponsible,
  productFetch,
  updateRelatedProduct,
  productPaginate,
  productFilterData,
  justificationTypes,
  newJustificationType,
  deleteJustificationType,
  showJustificationType,
  updateJustificationType,
  newTrasitTime,
  deleteTransitTime,
  transitTime,
  updateTransitTime,
  showTransitTime,
  supplierList,
  updateManyAlert,
  userSupplierList,
  newSupplier,
  responsibleSupplierList,
  carrier,
  client,
  deleteResponsibleSupplier,
  newUserSupplier,
  updateSupplier,
  updateOrderItem,
  country,
  listOrderFiles,
  createOrderFiles,
  searchOrderOptions,
  showOrderFiles,
  updateOrderFile,
  orderItemSelectedIdsReducer,
  orderItemJustificationMany,
  updateProcessCritical,
  exportOrderItemAlert,
  updateExportOrderItemAlert,
  updateManyExportOrderItemAlert,
  createUserSupplier
};