version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: kemira/Dockerfile
    container_name: kemira_comex_import_api
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
