apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cm03-import
  namespace: wc09
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cm03-import
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80