export * from "./account";
export * from "./auth";
export * from "./config";
export * from "./addressLookup";

import { actions, modules, permission, filters } from "./account";

import { fetchAddressByZipcode, listCities } from "./addressLookup";

import {
  login,
  auth,
  logout,
  generatePasswordResetToken,
  resetPassword,
  impersonate,
} from "./auth";

import {
  users,
  user,
  newuser,
  updateUser,
  deleteUser,
  userImage,
  roles,
  role,
  newrole,
  updateRole,
  deleteRole,
  userSecondaryEmailCreate,
  userSecondaryEmailDelete,
  alertTypeModuleId,
  paginateCarriers,
  createCarrier,
  listCountries,
  fetchCarrier,
  updateCarrier,
  deleteCarrier,
  paginateClients,
  createClient,
  fetchClient,
  updateClient,
  deleteClient,
  createTrackingTransitTime,
  paginateTrackingTransitTimes,
  updateTrackingTransitTime,
  fetchTrackingTransitTime,
  deleteTrackingTransitTime,
  listJustificationTypes,
  paginateCompanies,
  fetchCompanies,
  fetchAccounts,
  createCompany,
  updateCompany,
} from "./config";

export const generalReducers = {
  actions,
  modules,
  permission,
  login,
  auth,
  logout,
  generatePasswordResetToken,
  resetPassword,
  impersonate,
  users,
  user,
  newuser,
  updateUser,
  deleteUser,
  userImage,
  roles,
  role,
  newrole,
  updateRole,
  deleteRole,
  userSecondaryEmailCreate,
  userSecondaryEmailDelete,
  alertTypeModuleId,
  fetchAddressByZipcode,
  listCountries,
  paginateClients,
  createClient,
  fetchClient,
  updateClient,
  deleteClient,
  paginateCarriers,
  createCarrier,
  fetchCarrier,
  updateCarrier,
  deleteCarrier,
  createTrackingTransitTime,
  paginateTrackingTransitTimes,
  updateTrackingTransitTime,
  fetchTrackingTransitTime,
  deleteTrackingTransitTime,
  listCities,
  listJustificationTypes,
  paginateCompanies,
  fetchCompanies,
  fetchAccounts,
  createCompany,
  updateCompany,
  filters,
};
