apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iff-comex-import-api
  namespace: iff
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iff-comex-import-api
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80